### PR TITLE
Feature/9

### PR DESCRIPTION
**Pull request by JesusLegaspy**
fixed issue #9, #11, #12, #13

### CODE REVIEW

**Comment by kqarryzada** [comment]
Everything looks good, approved!

**Comment by JesusLegaspy** [comment]
Was this merged? I don't see it updated on master..

**Comment by JesusLegaspy** [comment]
I overrided and merged. all done!

**Comment by kqarryzada** [comment]
Oops, I missed a bit of a critical step. Thanks for taking care of it!

**Pull request merged**
